version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: book_postgres
    restart: always
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpass
    ports:
      - "5432:5432"
    networks:
      - booknet
    volumes:
      - pgdata:/var/lib/postgresql/data

  book-service:
    image: aruntmca/book-service:latest
    container_name: book_service
    depends_on:
      - postgres
    ports:
      - "1000:1000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookdb
      SPRING_DATASOURCE_USERNAME: bookuser
      SPRING_DATASOURCE_PASSWORD: bookpass
    networks:
      - booknet

networks:
  booknet:

volumes:
  pgdata:
