spring:
  application:
    name: book-service

  datasource:
    url: jdbc:postgresql://postgres:5432/bookdb
    username: bookuser
    password: bookpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 1000
  servlet:
    context-path: /book-service
